src/cluster/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    url(r'^$', views.index, name='inicio'),
    url(r'^principal/$', views.index, name='index'),
    url(r'^principaldemo/$', views.principal_demo, name='index'),
    url(r'^bd/$', views.bd, name='bd'),
    url(r'^estatisticas/$', views.estatisticas, name='estatisticas'),
    url(r'^cluster/$', views.cluster, name='cluster'),
    url(r'^poi/$', views.PoiIdentification.as_view(), name='poi'),
    url(r'^graficos/$', views.graficos, name='graficos'),
    url(r'^exportacao/$', views.Export.as_view(), name='exportacao'),
    url(r'^exportacao/download_database/$', views.baixar, name='baixar'),
    url(r'^exportacao/download_poi/$', views.baixar_poi, name='baixar_poi'),
    url(r'^cadastro/$', views.cadastro, name='cadastro'),
    url(r'^login/$', views.do_login, name='login'),
    url(r'^login$', views.do_login, name='login'),
    url(r'^logout/$', views.do_logout, name='logout'),
]

src/dcluster/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^', include('cluster.urls')),
    url(r'', include('cluster.urls', namespace="cluster", app_name="cluster")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cluster/models.py
from django.db import models

# Create your models here.

src/cluster/poi_detection/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from ..algoritmos.poi_identification.points_of_interest_job import PointOfInterest

#@method_decorator(login_required, name='dispatch')
class PoiIdentification(View):
    template_name = 'cluster/poi_detection.html'


    def get(self, request, *args, **kwargs):

        type = request.GET.get('type')
        if type is not None:
            if type == "fill_user_id_data_table":
                latitude_column = request.session['dado'].latitude_column
                longitude_column = request.session['dado'].longitude_column
                user_id_column = request.session['dado'].user_id_column
                datetime_column = request.session['dado'].datetime_column
                print("pesquisa", latitude_column, longitude_column, user_id_column, datetime_column)
                if len(latitude_column) == 0 or len(longitude_column) == 0 or len(user_id_column) == 0 or \
                        len(datetime_column) == 0:
                    error = "The given dataset doesn't have a latitude, longitude, user_id or datetime column to perform POI identification"
                    return HttpResponse(json.dumps({"message": error}), content_type="applicantion/json", status=301)
                else:

                    df = request.session['dado'].get_df()
                    users_id = df[user_id_column].unique().tolist()
                    max_ids = 1000
                    users_id = users_id[:max_ids]
                    return HttpResponse(json.dumps({"users_id": users_id}), content_type="applicantion/json")

        return render(request, 'cluster/poi.html')

    def post(self, request, *args, **kwargs):

        poi_identified = request.session['dado'].poi_identified
        print("possst", request.POST)
        selected_user_id = request.POST.get("user_identifier[]")
        print("usuariooooo", selected_user_id)
        # if selected_user_id is None:
        #     error = "Select a user identifier"
        #     return HttpResponse(json.dumps({"message": error}), content_type="applicantion/json", status=300)
        selected_columns = ['id', 'latitude', 'longitude', 'poi_type']
        poi = PointOfInterest()

        if poi_identified is None:
            columns = self.check_df_columns(request)
            if len(columns) == 0:
                return render(request, 'cluster/poi.html')
            else:
                latitude_column, longitude_column, user_id_column, datetime_column = columns
                users_steps = request.session['dado'].get_df()
                method = request.POST.get("method")
                minimum_samples = request.POST.get("minimum_samples")
                eps = request.POST.get("eps")
                minimum_samples_on_different_days = request.POST.get("minimum_samples_on_different_days")
                print(method, minimum_samples_on_different_days, minimum_samples, eps)
                poi_identified = poi.start(users_steps, user_id_column, latitude_column, longitude_column,
                                           datetime_column, method, minimum_samples, eps, minimum_samples_on_different_days)[selected_columns]
                dado = request.session['dado']
                dado.poi_identified = poi_identified
                request.session['dado'] = dado
                user_poi = poi_identified[poi_identified['id']==selected_user_id]
                user_poi = poi.convert_df_to_dict(user_poi)
                if len(user_poi['id']) == 0:
                    error = "No POI was found for the selected user"
                    return HttpResponse(json.dumps({"message": error}), content_type="applicantion/json", status=302)
                print("user poi: ", user_poi)
                return HttpResponse(json.dumps(user_poi), content_type="applicantion/json")
        else:
            print(poi_identified)
            user_poi = poi_identified[poi_identified['id']==selected_user_id]
            user_poi = poi.convert_df_to_dict(user_poi)
            print("Pois encontrados: ", user_poi)

            if len(user_poi['id']) == 0:
                error = "No POI was found for the selected user"
                return HttpResponse(json.dumps({"message": error}), content_type="applicantion/json", status=303)

            return HttpResponse(json.dumps(user_poi), content_type="applicantion/json")

    def check_df_columns(self, request):
        latitude_column = request.session['dado'].latitude_column
        longitude_column = request.session['dado'].longitude_column
        user_id_column = request.session['dado'].user_id_column
        datetime_column = request.session['dado'].datetime_column

        if len(latitude_column) == 0 or len(longitude_column) == 0 or len(user_id_column) == 0 or \
                len(datetime_column) == 0:
            return ()
        else:
            return latitude_column, longitude_column, user_id_column, datetime_column

src/cluster/views.py
# -*- coding: UTF-8 -*-
from django.shortcuts import render
import sys

# Create your views here.
from django.http import HttpResponse, HttpResponseNotFound
import json
from .modelos.dado import *
from .modelos.grafico import *
from .algoritmos.agrupamento import *
from .db_connect import *
from .forms import BancoForm
from django.shortcuts import render, redirect
from .forms import UserModelForm, RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .poi_detection.views import PoiIdentification
from .views_files.export import Export

def cadastro(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Obrigado por se cadastrar!')  # <-
            return redirect('/cadastro')
        else:
            messages.warning(request, 'Dados fornecidos são inválidos!')
            return redirect('/cadastro')

    form = RegisterForm()
    context = {'form': form}
    return render(request, 'cluster/cadastro.html', context)

def do_login(request):
    if request.method == 'POST':
        user = authenticate(username = request.POST['username'], password = request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect('/principal')
        else:
            messages.warning(request, 'Nome de usuário inválido ou senha incorreta!') # <-

    return render(request, 'cluster/login.html')

def do_logout(request):
    logout(request)
    return redirect('/login')

def inicio(request):
    return render(request, 'cluster/home.html', {})


def index(request):
        if request.POST:
                if request.FILES:
                        df, nome, sucesso = handle_uploaded_file(request)
                        if(sucesso == 1):
                                request.session['dado'] = Dado(df, nome)
                        else:
                                messages.warning(request,'Formato de arquivo inválido ou estrutura do arquivo fora do padrão de análise!')
                                return render(request, 'cluster/meu-arquivo.html')
                        a=request.session['dado'].get__Atributos()
                        for b in a:
                                pass
                        tb_arquivo = {"tipo":"csv", "nome":nome, "tamanho":request.FILES["csv_file"].size/1000}
                        request.session['tb_arquivo'] = tb_arquivo
                        nomes = json.dumps(request.session['dado'].get_NomeAtributos())
                        return render(request, 'cluster/meu-arquivo.html', tb_arquivo)
                #return HttpResponse( json.dumps(tb_arquivo), content_type="applicantion/json")
               # return HttpResponse(json.dumps(request.session['dado'].get_NomeAtributos()), content_type="application/json")
                #return render(request, 'cluster/meu-arquivo.html')

                elif str(request.POST.get('tipo'))=="banco-conexao":
                        try:
                                df = db_connection(request.POST.get('tipo_banco'), request.POST.get('url'),
                                                   request.POST.get('usuario'), str(request.POST.get('senha')),
                                                   request.POST.get('banco'), request.POST.get('consulta'),
                                                   request.POST.get('dsn'))
                                if not df.empty:
                                        nome = request.POST.get('banco')
                                        for col in df.columns:
                                                if df[col].dtype == 'object':
                                                        try:
                                                                df[col] = pd.to_datetime(df[col],
                                                                                         infer_datetime_format=True)
                                                        except:
                                                                pass
                                        request.session['dado'] = Dado(df, nome)
                                        return render(request, 'cluster/meu-arquivo.html', request.session['tb_arquivo'])
                                else:
                                        #print(df)
                                        return render(request, 'cluster/meu-arquivo.html')
                        except Exception as e:
                                return HttpResponse(json.dumps({"message": e}), content_type="applicantion/json",
                                                    status=301)

                elif str(request.POST.get('tipo')) == "demo_file":
                        df = pd.read_csv("src/cluster/arquivos/demo.csv", infer_datetime_format=True)
                        df['local_datetime'] = pd.to_datetime(df['local_datetime'], infer_datetime_format=True)
                        size = str(sys.getsizeof(df)/1000)
                        name = "Demo"
                        request.session['dado'] = Dado(df, name)
                        tb_arquivo = {"tipo": "csv", "nome": name, "tamanho": size}
                        request.session['tb_arquivo'] = tb_arquivo
                        return render(request, 'cluster/meu-arquivo.html', tb_arquivo)
                else:
                        messages.warning(request, 'Nenhum arquivo fornecido!')
                        return render(request, 'cluster/meu-arquivo.html')

        else:
                try: 
                        return render(request, 'cluster/meu-arquivo.html',  request.session['tb_arquivo'])
                except:
                        #request.session.clear()
                        return render(request, 'cluster/meu-arquivo.html')


def principal_demo(request):
        df = pd.read_csv("src/cluster/arquivos/demo.csv", infer_datetime_format=True)
        df['local_datetime'] = pd.to_datetime(df['local_datetime'], infer_datetime_format=True)
        size = str(sys.getsizeof(df) / 1000)
        name = "Demo"
        request.session['dado'] = Dado(df, name)
        tb_arquivo = {"tipo": "csv", "nome": name, "tamanho": size}
        request.session['tb_arquivo'] = tb_arquivo
        return render(request, 'cluster/meu-arquivo.html', tb_arquivo)


def bd(request):
        form = BancoForm()
        if request.POST:
                '''if str(request.POST.get('tipo'))=="banco-conexao":
                        print("\nbd")
                        print(request.POST.get('tipo_banco'), request.POST.get('url'), request.POST.get('usuario'), request.POST.get('senha'), request.POST.get('banco'), request.POST.get('consulta'), request.POST.get('dsn'))
                        df = db_connection(request.POST.get('tipo_banco'), request.POST.get('url'), request.POST.get('usuario'), request.POST.get('senha'), request.POST.get('banco'), request.POST.get('consulta'), request.POST.get('dsn'))
                        print(df.empty)
                        if not df.empty:
                                print("\nc")
                                request.session['dado'] = Dado(df, request.POST.get('banco'))
                                tb_arquivo = {"tipo":"mysql db", "nome":request.POST.get('banco'), "tamanho":str(len(df.to_csv(index_label=False, index=False, encoding='utf-8'))/1000)}
                                request.session['tb_arquivo'] = tb_arquivo
                                return HttpResponse( json.dumps(request.session['tb_arquivo']), content_type="applicantion/json")
                        else:
                                print("\ne")
                                #print(df)
                                return render(request, 'cluster/bd.html')'''
                info = BancoForm(request.POST)
                if info.is_valid():
                        
                        #print(request.POST.get('tipo_banco'), request.POST.get('url'), request.POST.get('usuario'), request.POST.get('senha'), request.POST.get('banco'), request.POST.get('consulta'), request.POST.get('dsn'))
                        try:
                                
                                df = db_connection(info.cleaned_data['tipo'], info.cleaned_data['url'], info.cleaned_data['usuario'], info.cleaned_data['senha'], info.cleaned_data['banco'], info.cleaned_data['consulta'], "1")
                        except:
                                return HttpResponseNotFound('<h1>Conexão inválida</h1>')
                        if not df.empty:
                                request.session['dado'] = Dado(df, info.cleaned_data['banco'])
                                tb_arquivo = {"tipo":"mysql db", "nome": info.cleaned_data['banco'], "tamanho":str(len(df.to_csv(index_label=False, index=False, encoding='utf-8'))/1000)}
                                request.session['tb_arquivo'] = tb_arquivo
                                #return HttpResponse( json.dumps(request.session['tb_arquivo']), content_type="applicantion/json")
                                tb_arquivo = {"tipo": request.session['tb_arquivo']['tipo'], "nome": request.session['tb_arquivo']['nome'], "tamanho": request.session['tb_arquivo']['tamanho'], "form": form}
                                return render(request, 'cluster/bd.html', tb_arquivo)
                        return render(request, 'cluster/bd.html', {'form': form})
        else:
                
                try:
                        info = {"tipo": request.session['tb_arquivo']['tipo'], "nome": request.session['tb_arquivo']['nome'], "tamanho": request.session['tb_arquivo']['tamanho'], "form": form}
                        return render(request, 'cluster/bd.html', info)
                except:
                        #request.session.clear()

src/cluster/templates/cluster/arquivos_gerais.html
 $('#addr'+i).html("<td>"+ (i+1) +"</td><td><input name='name"+i+"' type='text' placeholder='Name' class='form-control input-md'  /> </td><td><input  name='mail"+i+"' type='text' placeholder='Mail'  class='form-control input-md'></td><td><input  name='mobile"+i+"' type='text' placeholder='Mobile'  class='form-control input-md'></td>");

      $('#tab_logic').append('<tr id="addr'+(i+1)+'"></tr>');

src/cluster/templates/cluster/basic.html
{% extends "personal/header.html" %}

{% block content %}
	{% for c in content %}
		<p>{{c}}</p>
	{% endfor %}
{% endblock %}

src/cluster/templates/cluster/bd.html
{% extends "cluster/header.html" %}
{% block bd %}
{% load static %}
<script type="text/javascript" src="{% static 'cluster\java_script_files\bd.js' %}"></script>

<br>
<div class="col-lg-12">
    <div class="well"> <strong>Database conection</strong></div>
	<br>
</div>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="panel panel-deafult">
			<div class="panel-body">


			<div class="row-fluid" id="meu-arquivo-div-sgbd">
				<br>
				<div class="col-lg-6">
				<form id="meu-arquivo-banco" action="/bd/" method="post">
					{% csrf_token %}
					

					
					<!--<label>Tipo do banco de dados</label>
					<div class="row-fluid">
					<div class="col-lg-6">
					<div class="radio">
						<label>
							<input type="radio" name="optionsRadios" id="mysql" value="mysql" checked>
							MySQL
						</label>
					</div>
					</div>
					<div class="col-lg-6">
					<div class="radio">
						<label>
							<input type="radio" name="optionsRadios" id="optionsRadios2" value="sqlserver">
							SQL Server
						</label>
					</div>
					</div>
					</div>-->
					<!--<label>URL</label>
					<input type="text" class="form-control" value="localhost" id="url" name='url' placeholder="url">
					<label>Base de dados</label>
					<input type="text" class="form-control" value="bd" id="banco" name='banco' placeholder="nomedobanco">
					<label>Usuário</label>
					<input type="text" class="form-control" value="root" id="usuario" name='usuario' placeholder="usuário">
					<div id="div-dsn">
					<label>DSN</label>
					<input type="text" class="form-control" value="eu" id="dsn" name='dsn' placeholder="dsn">
					</div>
					<label>Senha</label>
					<input type="password" class="form-control" value="25252525" id="senha" name='senha' placeholder="senha">
					<label>Consulta</label>
					<input type="text" class="form-control" id="consulta" value="SELECT * FROM bd.t1;" name='consulta' placeholder="select * from nomedatabela">-->
					{{ form }}
					<br>
					<input class="btn btn-default" type="submit" value="Confirm" />
				</form>
				<!--<button id="confirma-banco" type="button" class="btn btn-default">Confirmar</button>-->
				</div>
				<div class="col-lg-6">
				<div class="panel panel-default">
  <div class="panel-heading" style="margin:0px">Current dataset</div>
  <div class="row-fluid">
    {% include "cluster/includes/info-meu-arquivo.html" %}
  </div>
</div>
					
				</div>
			</div>
			</div>
		</div>
	</div>
</div>
<style>
div {
	height : 200;
    width : 300;
    display : block;
}
</style>
<!--style="height: 525; width: 100%;" <script type="text/javascript" src="C:\Users\claud\Documents\Projeto\part8\mysite\cluster\templates\cluster\home_script.js"></script>{% include "cluster/includes/htmlsnippet.html" %}-->

<script type="text/javascript">
$(document).ready(function() {
	
	$('#div-dsn').hide();
	$('input[name=optionsRadios]').change(function(){

		if($( 'input[name=optionsRadios]:checked' ).val() == "mysql"){
			$('#dsn').html('');
			$('#div-dsn').hide();
		}
		else{
			$('#div-dsn').show();
			$('#url').val('DESKTOP-UDR87N3');
			$('#usuario').val('claud');
			$('#senha').val('Mano3536');
			$('#consulta').val("SELECT regiao as 'Regiao', count(regiao) as 'Contagem carro' FROM t4.dbo.cliente as c join t4.dbo.carro as c3 on c.id_cliente = c3.cliente_id_cliente group by regiao")
		}
	});
	

});


function confirmar_banco() {
	
		$.ajax({
			method: 'POST',
			url: '',
			//method: 'GET',
			//data: {}, // appears as $_GET['id'] @ your backend side jQuery.ajax
			dataType: "json",
            async: false,
			data: { tipo: 'banco-conexao',
				csrfmiddlewaretoken: '{{ csrf_token }}',
				url: $('#url').val(),
				banco: $('#banco').val(),
				usuario: $('#usuario').val(),
				senha: $('#senha').val(),
				consulta: $('#consulta').val(),
				tipo_banco: $( 'input[name=optionsRadios]:checked' ).val(),
				dsn: $('#dsn').val()},
			success: function(dataSet, status){
				window.location.href = "http://127.0.0.1:8000/bd/";
				
			}
		});

	
	

}

</script>

{% endblock %}

src/cluster/templates/cluster/cadastro.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'cluster/images/favicon.ico' %}" type="image/x-icon">
	<link rel="icon" href="{% static 'cluster/images/favicon.ico' %}" type="image/x-icon">

    <title>Página Cadastro</title>

    <!-- Bootstrap core CSS -->
    <link href= "{% static 'cluster/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	
	<link href= "{% static 'cluster/css/signin2.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
	  
      <form action = "{% url 'cluster:cadastro' %}" class="form-signin", method = "post">
	    {% csrf_token %}
        <h2 class="form-signin-heading">Register</h2>
		<fieldset>
			{% for field in form %}
				{{ field.label_tag }}
				{{ field }}
				{{ field.errors }}
				<br/>
				<br/>
			{% endfor %}
			
			<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
			</br>
			</br>
			<a href = "{% url 'cluster:login' %}">Login page</a></br></br>
			<a href = "http://127.0.0.1:8000/">Home page</a>
		</fieldset>
		<br/>
		<div id = "mensagem-cadastro">
		{% if messages %}
			{% for message in messages %}
				<p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
			{% endfor %}
		{% endif %}
		</div>
      </form>

    </div> <!-- /container -->

  </body>
</html>

src/cluster/templates/cluster/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		
		<link rel="icon" href="{% static 'cluster/images/favicon.ico">
		
		<title>DCluster - Home</title>
		

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CVarela+Round" rel="stylesheet">

		<!-- Bootstrap -->
		<link  type="text/css" rel="stylesheet" href= "{% static 'cluster/bootstrap/css/bootstrap.min.css' %}" >

		<!-- Owl Carousel -->
		<link type="text/css" rel="stylesheet" href= "{% static 'cluster/bootstrap/css/owl.carousel.css' %}">
		<link type="text/css" rel="stylesheet" href= "{% static 'cluster/bootstrap/css/owl.theme.default.css' %}">

		<!-- Magnific Popup -->
		<link type="text/css" rel="stylesheet" href= "{% static 'cluster/bootstrap/css/magnific-popup.css' %}">

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href= "{% static 'cluster/bootstrap/css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href= "{% static 'cluster/bootstrap/css/style.css' %}">
		
		 <link rel="shortcut icon" href="{% static 'cluster/images/favicon.ico' %}" type="image/x-icon">
		<link rel="icon" href="{% static 'cluster/images/favicon.ico' %}" type="image/x-icon">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>
		<!-- Header -->
		<header id="home">
			<!-- Background Image -->
			<div class="bg-img" style="background-image: url('{% static 'cluster/images/analise-exploratoria.jpg' %}');">
				<div class="overlay"></div>
			</div>
			<!-- /Background Image -->

			<!-- Nav -->
			<nav id="nav" class="navbar nav-transparent">
				<div class="container">

					<div class="navbar-header">
						<!-- Logo -->
						<div class="navbar-brand">
							<a href="http://127.0.0.1:8000/principal/">
								<img class="logo-alt" src="{% static 'cluster/images/logo/logo.png' %}" alt="logo">
							</a>
						</div>
						<!-- /Logo -->

						<!-- Collapse nav button -->
						<div class="nav-collapse">
							<span></span>
						</div>
						<!-- /Collapse nav button -->
					</div>
					
					<!--  Main navigation  -->
					<!-- <ul class="main-nav nav navbar-nav navbar-right">  
						<li><a href="#home">Home</a></li>
						<li><a href="#about">About</a></li>
						<li><a href="#portfolio">Portfolio</a></li>
						<li><a href="#service">Services</a></li>
						<li><a href="#pricing">Prices</a></li>
						<li><a href="#team">Team</a></li>
						<li class="has-dropdown"><a href="#blog">Blog</a>
							<ul class="dropdown">
								<li><a href="blog-single.html">blog post</a></li>
							</ul>
						</li>
						<li><a href="#contact">Contact</a></li>
					</ul> -->
					<!-- /Main navigation -->

				</div>
			</nav>
			<!-- /Nav -->

			<!-- home wrapper -->
			<div class="home-wrapper">
				<div class="container">
					<div class="row">

						<!-- home content -->
						<div class="col-md-10 col-md-offset-1">
							<div class="home-content">
								<h1 class="white-text">DCluster: georeferenced analytics</h1>
{#								<p class="white-text">Um sistema que visa auxiliar analistas de dados na exploração e visualização de#}
{#								grandes volumes de tipos variados de dados, incluindo os georreferenciados.#}
{#								</p>#}
								<a href="{% url 'cluster:cadastro' %}">
									<button class="white-btn">Register</button>
								</a>
								<a href="{% url 'cluster:login' %}">
									<button class="main-btn">Sign-in</button>
								</a>
							</div>
						</div>
						<!-- /home content -->

					</div>
				</div>
			</div>
			<!-- /home wrapper -->

		</header>
		<!-- /Header -->
	</body>
</html>

src/cluster/templates/cluster/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'cluster/images/favicon.ico' %}" type="image/x-icon">
	<link rel="icon" href="{% static 'cluster/images/favicon.ico' %}" type="image/x-icon">

    <title>Página Login</title>

    <!-- Bootstrap core CSS -->
    <link href= "{% static 'cluster/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	
	<link href= "{% static 'cluster/css/signin2.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="container">

      <form action = "{% url 'cluster:login' %}" class="form-signin", method = "post">
	    {% csrf_token %}
        <h2 class="form-signin-heading">Login</h2>
        <div class = "form-group">
			<div class = "col-md-12">
				<h3>Username</h3>
				<input type = "text" name = "username" class = "form-control" placeholder = "Login" />
			</div>
		</div>
		
		 <div class = "form-group">
			<div class = "col-md-12">
				<h3>Password</h3>
				<input type = "password" name = "password" class = "form-control" placeholder = "Senha" />
			</div>
		</div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Confirm</button>
		<br/>
		<div id = "erro-login">
		{% if messages %}
			{% for message in messages %}
				<p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
			{% endfor %}
		{% endif %}
		</div>
		<br/>
		<a href = "{% url 'cluster:cadastro' %}">Register here</a></br></br>
		<a href = "http://127.0.0.1:8000/">Home page</a>
      </form>

    </div> <!-- /container -->

  </body>
</html>